config/routes.rb
McafeeExercises::Application.routes.draw do
  
  root :to => "home#index"

  get "ex_one" => "home#ex_one", :as => :one
  get "ex_two" => "home#ex_two", :as => :two
  get "result" => "home#result", :as => :result
  get "primes" => "home#primes", :as => :primes

  get "home/ex_two_form"
  

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  include ApplicationHelper
  
  def index
  end

  def ex_one
  	response = GET("www.mcafee.com")

  	redirect_to result_path(:response => response, :ex => "1")
  end

  def ex_two
  	#nothing to do here
  end

  def ex_two_form
  	max_number = params[:max_number].to_i
  	#array = ComputePrimesDescending(max_number)
  	redirect_to primes_path(:ex => "2", :max_number => max_number.to_s)
  end

  def primes

  	max_number = params[:max_number].to_i
  	@array = ComputePrimesDescending(max_number)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	require 'socket'
	include Socket::Constants

	# Methods created for Ex 1

	def GET(host)		

		port = 80

		# Creating request
		request = "GET HTTP/1.0\r\n\r\n"

		# Creating new socket
		socket = Socket.new(AF_INET, SOCK_STREAM, 0)
		# Configuring connection params in socket (port, URL)
		sockaddr = Socket.sockaddr_in(port, host)
		# Starting connection and sending request.
		socket.connect(sockaddr)
		socket.send(request, 0)
		
		# Getting response, closing socket and redirecting user to the results view
		response = socket.recv(4095)
		puts response

		socket.close

		return response.to_s
		
	end

	# Methods created for Ex 2

	def ComputePrimesDescending(max_number)

		array = []
		array << 1
		array << 2		
		for i in 3..max_number

			is_prime = true

			for j in 2..i-1
				if i % j == 0
					is_prime = false
					break
				end
			end

			if is_prime
				array << i
				is_prime = true
				puts i
			end
		end

		#puts array.reverse
		return array.reverse
	end
end

app/views/home/ex_two.erb
<div style="margin-left:25px!important; margin-right:25px!important;">
	Using <b>ComputePrimesDescending</b> method:
	<br /><br />

	<form action="<%= home_ex_two_form_path%>">
		 N value (put any integer > 1):
		 <br />
		 <input type="text" name="max_number">
		 <br /><br />
		 <input value="Get primes" type="submit" class="btn btn-success"/>
	</form>
</div>

app/views/home/primes.erb
<div style="margin-left:25px!important; margin-right:25px!important;">
	<p>Method Complexity: O(n^2)</p>
	<p>Getting all prime numbers up to <%= params[:max_number]%>. Showing results:</p>
	<p><%= @array.to_s %></p>	
</div>

app/views/home/result.erb
<div style="margin-left:25px!important; margin-right:25px!important;">
	<% if params[:ex] == "1"%>
		<p>HTTP GET Request made to <b>www.mcafee.com</b>. Showing results:</p>
		<br /><br />
		<p><%= params[:response].to_s %></p>
	<% end %>

	<% if params[:ex] == "2"%>
		<p>Getting all prime numbers up to <%= params[:max_number]%>. Showing results:</p>
		<p><%= params[:array].to_s %></p>	
	<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to  "Ex 1", one_path %></li>
        <li><%= link_to  "Ex 2", two_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>McafeeExercises</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
	<body>
	<%= render "layouts/navbar" %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

	</body>
</html>